### ISSUE TITLE
stemming.yaml: PAP.DPF rule and δίδωμι

### ISSUE THREAD

**Issue by emg** [jtauber/greek-inflexion#29]
I am using this excellent library to generate paradigms for various verbs.  I am using the lexicon in STEM_DATA/morphgnt_lexicon.yaml, and stemming.yaml from the root of the repo.
I find that generating the form of δίδωμι with parsing PAP.DPF generates this:

διδο{athematic}ούσαις

It would obviously generate the wrong form is I just removed the {athematic} substring.

Looking in stemming.yaml, I find this rule commented out for PAP.DPF:

- "|ο{athematic}>ού<_|σαις"

If I uncomment this in, then the form becomes:

διδούσαις

which is, of course, correct.

I am not sure what other verbs would be affected by this change -- surely some others.  I have not yet checked whether this can be applied without negative effects.

Hope this helps, and many thanks to all contributors for all your hard work.

Best wishes,

Ulrik Sandborg-Petersen

**Comment by jtauber** [comment]
all tests pass when I uncomment it (not sure why I commented it out in the first place) so I'm going to push this fix. Many thanks for reporting it!
