### ISSUE TITLE
inflexion.conjugate(): {root} in output for unattested forms

### ISSUE THREAD

**Issue by jonathanrobie** [jtauber/greek-inflexion#3]
For some forms, inflexion.conjugate() includes the string "{root}".  I'm not sure, but this looks like it may happen when there is no attested root in the lexicon.

For instance:

```
inflexion.conjugate("ἀνίστημι", "AAN", "PAN", "PAD", "AMD", "PAI", "AAI", "PAP", "AAP", tags={"final-nu-aai.3s"})
```

is correct for most forms, but has {root} for some of the AMD forms:

    AMD.2S: ἀνάστα{root}αι/ἀνάστησαι
    AMD.3S: ἀναστα{root}άσθω/ἀναστησάσθω
    AMD.2P: ἀναστά{root}ασθε/ἀναστήσασθε
    AMD.3P: ἀναστα{root}άσθων/ἀναστησάσθων

**Comment by jtauber** [comment]
What is happening here is the (unaugmented) aorist stem is given in the stem database as `ἀναστησ/ἀναστα{root}` and the rule for (say) `AMD.2S` doesn't know how to handle root aorists so it falls back to the default "just add αι to the stem".

Unless I can find evidence of a distinct middle imperative form for root aorists, my inclination is to change the stem database to say AMDs ONLY have the stem ἀναστησ.

Given the root / sigmatic aorist alternation was classically to do with transitivity, it makes sense it may not exist in the middle.

**Comment by jonathanrobie** [comment]
Yes, that would be helpful.  For my particular use case, I would prefer to see a positive sign that a form is not attested.  Often, I may expect to find either a middle form or an active form but not both, and I just want to know which one exists.

**Comment by jtauber** [comment]
The point of the library, though, is to tell you what the form WOULD be. Whether it's attested or not takes a corpus search.

**Comment by jonathanrobie** [comment]
OK, that's reasonable.

**Comment by jtauber** [comment]
To be clear, you're reporting a valid bug which I'll fix. But knowing whether a certain form is _attested_ is a separate issue. But note that even then, I'm not talking about active vs middle, but root vs sigmatic.

**Comment by jtauber** [comment]
this has (finally) been addressed, assuming only the ἀναστησ- forms are valid
