### ISSUE TITLE
morphgnt_lexicon.yaml: unattested 3- stems of τίθημι

### ISSUE THREAD

**Issue by emg** [jtauber/greek-inflexion#30]
Hi,

In STEM_DATA/morphgnt_lexicon.yaml, I found this line:

3-: θησ/θε{athematic}

I am guessing this is intended to say that there are two stems for certain aorist forms, delimited by the slash.

I haven't found any aorist forms in the Greek New Testament (Nestle 1904, to be exact) where either stem is attested.  Am I misinterprething this line?

If not, should it be deleted from the morphgnt_lexicon.yaml?

Many thanks.

Best wishes,

Ulrik Sandborg-Petersen

**Comment by emg** [comment]
Oops... I see now that it means 2nd aorist, and some of those do exist for τίθημι in the GNT.

But then, only the  'θε{athematic}' stem is found for this lemma, not 'θησ'.

Hope this helps.

Best wishes,

Ulrik

**Comment by emg** [comment]
Oops again... The  θησ stem does exist as an aorist in the GNT.  But only the form QH/SW, which of course is AAS.1S.  There are some more future forms which have θησ as the stem.

Am I right that 3- is meant to be 2nd aorist?

Many thanks,

Ulrik

**Comment by emg** [comment]
Returning to this, I find that the 'θε{athematic}' stem generates a lot of forms in the paradigm for τίθημι which are not true forms. Examples include:

 θέ{athematic}ωσι	τίθημι	AAS.3P
 θε{athematic}αμένᾱς	τίθημι	AMP.APF
 θε{athematic}αμένους	τίθημι	AMP.APM
 θε{athematic}άμενα	τίθημι	AMP.APN
 θε{athematic}αμένην	τίθημι	AMP.ASF
 θε{athematic}αμέναις	τίθημι	AMP.DPF
 θε{athematic}αμένοις	τίθημι	AMP.DPM

If we try to remove the '{athematic}' substring from these, things go wrong.

One solution might be to add a lot of rules to stemming.yaml which mention the ε{athematic} sub-part of the SandhiRule.  In that case, a lot of rules have to be added to stemming.yaml.  I see that a lot of these rules have, in fact, been added, but have been commented out again. Perhaps this is because the problem goes deeper than that?

I am afraid I don't know how to resolve it.  If I can help, I would be happy to do some work and send a pull request. I would need to be told what to do, though.

Many thanks,

Ulrik

**Comment by jtauber** [comment]
`3-` is the stem for non-indicative aorists. So the θησ stem makes sense for AAS.1S.

I think the only error is what you report in your last comment which is simply that the stemming.yaml don't yet handle ε-athematics in a few cells. I'm investigating now.

**Comment by jtauber** [comment]
there were a couple more commented out rules in stemming.yaml. Uncommenting them seemed to fix everything. I've written a regression test for all the stuff you've reported and it all passes now.
