### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by jcuenod** [jtauber/greek-inflexion#4]
I suspect that this is simply that I'm not using the library correctly but when I run

    inflexion.parse("ἀπεχόμενος")

I get:

    set()

I thought it was a normalisation issue but it doesn't seem to be. What am I doing wrong?

**Comment by jtauber** [comment]
What lexicon file are you using and it does it have the necessary verb stem?

**Comment by jcuenod** [comment]
Ahh, I was using `pratt_lexicon.yaml` but thanks, I grabbed the `lxx_lexicon` from your lxx branch and got expected results...

**Comment by jtauber** [comment]
At some stage I'll separate out the "lexicon" from the library more cleanly. Sorry for any confusion.
